#!/bin/bash
# Dzjio Skripting
# 12 januari 2017
# Gersom Zomer & Yannick Mijnheer

#change to the data directory
cd ~/Data/

#copy the file for processing
cp LE71700552001036SGS00_SR_Gewata_INT1U.tif input.tif

#running the NDVI calculation
gdal_calc.py -A input.tif --A_band=4 -B input.tif --B_band=3  --outfile=rawNDVI.tif  --calc="(A.astype(float)-B)/(A.astype(float)+B)" --type='Float32'

#resample the output
gdalwarp -tr 60 60 -r cubic -overwrite rawNDVI.tif resNDVI.tif

#reproject the output
gdalwarp -t_srs EPSG:4326 -overwrite resNDVI.tif NDVI.tif

#cleaning up
rm input.tif rawNDVI.tif resNDVI.tif



